#!/usr/bin/env ruby

require 'tweetstream'
require 'twitter'
require 'trollop'
require 'json'

opts = Trollop.options do
  opt :twitter_config, 'Filename containing Twitter key config', type: String, default: File.expand_path('../twitter_conf.json', __FILE__)
end

config_file = opts[:twitter_config] or abort 'Twitter config file required'

twitter_config = JSON.parse(File.read(config_file))

TweetStream.configure do |config|
  config.consumer_key = twitter_config['consumer_key']
  config.consumer_secret = twitter_config['consumer_secret']
  config.oauth_token = twitter_config['access_token']
  config.oauth_token_secret = twitter_config['access_token_secret']
  config.auth_method = :oauth
end

client = TweetStream::Client.new

client.on_anything do |message|
  if message.has_key?(:event) && message[:event] == 'favorite'
    puts message[:target_object][:text]
  end
end

client.userstream
